/**
 * Typed content loader (spec §8.2 "typed loaders").
 *
 * The app imports the baked question bank from here. JSON is generated by
 * `npm run build:content` (scripts/build-content.mjs) from the xlsx. Run that
 * whenever the spreadsheet changes.
 */
import bank from "./generated/bank.json";
import type {
  ListQuestion,
  MCQuestion,
  NumericQuestion,
  QuestionBank,
} from "./types";

export const QUESTION_BANK = bank as unknown as QuestionBank;

export const ROUND1: MCQuestion[] = QUESTION_BANK.round1;
export const ROUND2: MCQuestion[] = QUESTION_BANK.round2;
export const ROUND3: NumericQuestion[] = QUESTION_BANK.round3;
export const FINAL: ListQuestion[] = QUESTION_BANK.final;

export * from "./types";
