/**
 * Typed content loader (spec §8.2 "typed loaders").
 *
 * The app imports the baked question bank from here. JSON is generated by
 * `npm run build:content` (scripts/build-content.mjs) from the xlsx. Run that
 * whenever the spreadsheet changes.
 */
import bank from "./generated/bank.json";
import fullFlagSupplement from "./full-flag-supplement.json";
import type {
  ListQuestion,
  MCQuestion,
  NumericQuestion,
  QuestionBank,
} from "./types";

const _bank = bank as unknown as QuestionBank;
export const QUESTION_BANK: QuestionBank = {
  ..._bank,
  round2: [..._bank.round2, ...(fullFlagSupplement as unknown as MCQuestion[])],
  counts: { ..._bank.counts, round2: _bank.counts.round2 + fullFlagSupplement.length, total: _bank.counts.total + fullFlagSupplement.length },
};

export const ROUND1: MCQuestion[] = QUESTION_BANK.round1;
export const ROUND2: MCQuestion[] = QUESTION_BANK.round2;
export const ROUND3: NumericQuestion[] = QUESTION_BANK.round3;
export const FINAL: ListQuestion[] = QUESTION_BANK.final;

export * from "./types";
